@startuml

title Car Number Generator. Sequence Diagram

autonumber

!include ../common/actors/actors.puml!Analyst
!include ../common/actors/actors.puml!EntryPoint
!include runner/runner.puml!PARTICIPANT
!include generator-cli/generator-cli.puml!PARTICIPANT
!include pattern-parser/pattern-parser.puml!PARTICIPANT
!include generator/generator.puml!PARTICIPANT
!include ../common/exporter/exporter.puml!PARTICIPANT

Analyst -> index: generate:numbers <args>
index -> Runner: run(args)

Runner -> GeneratorCli: parse(args)
Runner <- GeneratorCli: CliArguments\n{ pattern, definitions, output, count, shuffle }

Runner -> PatternParser: parse(pattern, definitions)
Runner <- PatternParser: facets: Facet[]

Runner -> Generator: generate(facets, { count, shuffle })
Runner <- Generator: numbers: CarNumber[]

Runner -> Exporter: export(output, numbers)
Runner <- Exporter: output\n(default: ./output/numbers.txt)

index <- Runner: output\n(default: ./output/numbers.txt)
Analyst <- index: output\n(default: ./output/numbers.txt)

@enduml