@startuml

class Generator {
    + generate(keySets: VoiceoverKey[][], dictionary: VoiceoverDictionary): Voiceover[]
}

@enduml

@startuml(id=GeneratorPrivate)

!include generator.puml

class Generator {
    - combinator: Combinator
    - getFacetByKeys(keySet: VoiceoverKey[], dictionary: VoiceoverDictionary): VoiceoverFacetSet
}

@enduml

@startuml(id=PARTICIPANT)
participant Generator
@enduml