@startuml

class Generator {
    + generate(keySets: VoiceoverKey[][], dictionary: VoiceoverDictionary, countPerKey?: number): Voiceover[]
}

@enduml

@startuml(id=GeneratorPrivate)

!include generator.puml

class Generator {
    - getFacetByKeys(keySet: VoiceoverKey[], dictionary: VoiceoverDictionary): VoiceoverFacetSet
    - cartesianProduct(facets: Facet[]): DisjointCombination[]
}

@enduml

@startuml(id=PARTICIPANT)
participant Generator
@enduml