@startuml

class Generator {
    + generate(facets: Facet[]): CarNumber[]
}

@enduml

@startuml(id=GeneratorPrivate)

!include generator.puml

class Generator {
    - combinator: Combinator
}

@enduml

@startuml(id=PARTICIPANT)
participant Generator
@enduml