@startuml
actor :П1.Оператор БД: as Actor.P1
rectangle "Генератор записей прочтения номеров" {
usecase UC.1.01 As "
ВИ.1.01.Сформировать
набор автомобильных
номеров для читалки
согласно заданному
шаблону"
Actor.P1 -> UC.1.01
usecase UC.1.02.01 As "
ВИ.1.02.01.Сформировать
набор вариантов
прочтения заданного
набора российских
номеров"
Actor.P1 -> UC.1.02.01
usecase UC.1.02.02 As "
ВИ.1.02.02.Сформировать
набор вариантов
прочтения заданного
набора латвийских
номеров"
Actor.P1 -> UC.1.02.02
usecase UC.1.02.03 As "
ВИ.1.02.03.Сформировать
набор вариантов
прочтения заданного
набора литовских
номеров"
Actor.P1 -> UC.1.02.03
usecase UC.1.02.04 As "
ВИ.1.02.04.Сформировать
набор вариантов
прочтения заданного
набора эстонских
номеров"
Actor.P1 -> UC.1.02.04
usecase UC.1.02.05 As "
ВИ.1.02.05.Сформировать
набор вариантов
прочтения заданного
набора финских
номеров"
Actor.P1 -> UC.1.02.05
usecase UC.1.02 As "ВИ.1.02.Сформировать
набор вариантов
прочтения заданного
набора номеров"
UC.1.02 <|-- UC.1.02.01
UC.1.02 <|-- UC.1.02.02
UC.1.02 <|-- UC.1.02.03
UC.1.02 <|-- UC.1.02.04
UC.1.02 <|-- UC.1.02.05
usecase UC.1.02.06 As "
ВИ.1.02.06.Варианты
прочтения формировать
на основании заданного
справочника символов"
UC.1.02.06 .> UC.1.02 : включает
usecase UC.1.02.07 As "
ВИ.1.02.07.Варианты
прочтения формировать
с приоритетом
длинных кодов"
UC.1.02.07 .> UC.1.02 : включает
usecase UC.1.02.08 As "
ВИ.1.02.08.Варианты
прочтения кодов со
спутниками формировать
и со спутниками и без"
UC.1.02.08 .> UC.1.02 : включает
}
@enduml