@startuml

title Voiceover Generator. Class Diagram

skinparam linetype ortho

!include runner/runner.puml
!include generator-cli/generator-cli.puml
!include car-numbers-reader/car-numbers-reader.puml
!include dictionary-reader/dictionary-reader.puml
!include generator/generator.puml
!include ../common/exporter/exporter.puml

Runner o-- GeneratorCli
Runner o-- CarNumbersReader
Runner o-- DictionaryReader
Runner o-- Generator
Runner o-- Exporter

@enduml