@startuml

actor :П1.Оператор БД: as Actor_P1

rectangle "Генератор записей прочтения номеров" as system_boundary {
    usecase UC_1_01 as "
    ВИ.1.01.Сформировать
    набор автомобильных
    номеров для читалки
    согласно заданному
    шаблону"

    usecase UC_1_02_01 as "
    ВИ.1.02.01.Сформировать
    набор вариантов
    прочтения заданного
    набора российских
    номеров"

    usecase UC_1_02_02 as "
    ВИ.1.02.02.Сформировать
    набор вариантов
    прочтения заданного
    набора латвийских
    номеров"

    usecase UC_1_02_03 as "
    ВИ.1.02.03.Сформировать
    набор вариантов
    прочтения заданного
    набора литовских
    номеров"

    usecase UC_1_02_04 as "
    ВИ.1.02.04.Сформировать
    набор вариантов
    прочтения заданного
    набора эстонских
    номеров"

    usecase UC_1_02_05 as "
    ВИ.1.02.05.Сформировать
    набор вариантов
    прочтения заданного
    набора финских
    номеров"

    usecase UC_1_02 as "ВИ.1.02.Сформировать
    набор вариантов
    прочтения заданного
    набора номеров"

    usecase UC_1_02_06 as "
    ВИ.1.02.06.Варианты
    прочтения формировать
    на основании заданного
    справочника символов"

    usecase UC_1_02_07 as "
    ВИ.1.02.07.Варианты
    прочтения формировать
    с приоритетом
    длинных кодов"

    usecase UC_1_02_08 as "
    ВИ.1.02.08.Варианты
    прочтения кодов со
    спутниками формировать
    и со спутниками и без"
}

Actor_P1 -right-> UC_1_01
Actor_P1 -right-> UC_1_02_01
Actor_P1 -right-> UC_1_02_02
Actor_P1 -right-> UC_1_02_03
Actor_P1 -right-> UC_1_02_04
Actor_P1 -right-> UC_1_02_05

UC_1_02 <|-right- UC_1_02_01
UC_1_02 <|-right- UC_1_02_02
UC_1_02 <|-right- UC_1_02_03
UC_1_02 <|-right- UC_1_02_04
UC_1_02 <|-right- UC_1_02_05

UC_1_02_06 .right.> UC_1_02 : <<включает>>
UC_1_02_07 .right.> UC_1_02 : <<включает>>
UC_1_02_08 .right.> UC_1_02 : <<включает>>

UC_1_01 -[hidden]down- UC_1_02

UC_1_02_06 -[hidden]down- UC_1_02_07
UC_1_02_07 -[hidden]down- UC_1_02_08

together uc_generalizing {
    UC_1_02_01 -[hidden]down- UC_1_02_02
    UC_1_02_02 -[hidden]down- UC_1_02_03
    UC_1_02_03 -[hidden]down- UC_1_02_04
    UC_1_02_04 -[hidden]down- UC_1_02_05
}

together uc_include {
    UC_1_02_06 -[hidden]down- UC_1_02_07
    UC_1_02_07 -[hidden]down- UC_1_02_08
}

uc_include -[hidden]right- UC_1_02
uc_include -[hidden]down- UC_1_01

@enduml