name: main

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      NPM_REGISTRY_ACCESS_TOKEN: ${{secrets.NPM_REGISTRY_ACCESS_TOKEN}}

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.15.0'
      - name: Install dependencies
        run: yarn --frozen-lockfile
      - name: Lint
        run: yarn lint
      - name: Test
        run: yarn test
      - name: Build
        run: yarn build